### ISSUE TITLE
image_classification ImportError: cannot import name 'Bottleneck4ResNet152'

### ISSUE THREAD

**Issue by andreamigliorati** [yoshitomo-matsubara/supervised-compression#28]
I'm trying to replicate your results by following the reported commands for image classification.

```
 # Image classification
for beta in 5.0e-11 1.0e-10 2.0e-10 4.0e-10 8.0e-10 1.6e-9 6.4e-9 1.28e-8
do
  echo 'beta=${beta}'
  pipenv run python image_classification.py -test_only --config configs/ilsvrc2012/singh_et_al/bottleneck_resnet50-b24ch_igdn-beta${beta}_from_resnet50.yaml
done
```

However, when running I get the following error:

```
  File "image_classification.py", line 24, in <module>
    from custom.classifier import InputCompressionClassifier, get_custom_model
  File "/media/HDD/migliorati/coding_machines/supervised-compression-main/custom/__init__.py", line 1, in <module>
    from custom import loss, misc, model, optim, transform, processor
  File "/media/HDD/migliorati/coding_machines/supervised-compression-main/custom/model.py", line 6, in <module>
    from torchdistill.models.custom.bottleneck.classification.resnet import Bottleneck4ResNet152, CustomResNet
ImportError: cannot import name 'Bottleneck4ResNet152'
```
I assume this module is needed as it's called by `custom_resnet50`. How can I make this work? Thanks in advance

**Comment by yoshitomo-matsubara** [comment]
Hi @andreamigliorati ,

What version of torchdistill are you using?
This repo is built on old torchdistill (<= 0.2.7)

**Comment by yoshitomo-matsubara** [comment]
If you cannot install old packages, you can use code for SC2 benchmark https://github.com/yoshitomo-matsubara/sc2-benchmark , significantly extended ver of [this repo](https://github.com/yoshitomo-matsubara/supervised-compression?tab=readme-ov-file#update-extended-version-of-this-wacv-paper).

**Comment by andreamigliorati** [comment]
Hi, thanks for the quick reply. Can you also tell me which `torchvision` version is the code made for? I have installed torchdistill=0.2.7 but I now get this error (which I am getting also using the sc2-benchmark).

```
/media/RAID/migliorati/venvpyto/lib/python3.10/site-packages/torchvision/models/segmentation/segmentation.py:7: UserWarning: The 'torchvision.models.segmentation.segmentation' module is deprecated since 0.12 and will be removed in 0.14. Please use the 'torchvision.models.segmentation' directly instead.
  warnings.warn(
Traceback (most recent call last):
  File "/media/RAID/migliorati/coding_machines/supervised-compression-main/image_classification.py", line 24, in <module>
    from custom.classifier import InputCompressionClassifier, get_custom_model
  File "/media/RAID/migliorati/coding_machines/supervised-compression-main/custom/__init__.py", line 1, in <module>
    from custom import loss, misc, model, optim, transform, processor
  File "/media/RAID/migliorati/coding_machines/supervised-compression-main/custom/model.py", line 17, in <module>
    from torchvision.models.segmentation.segmentation import model_urls as segm_model_urls
ImportError: cannot import name 'model_urls' from 'torchvision.models.segmentation.segmentation' (/media/RAID/migliorati/venvpyto/lib/python3.10/site-packages/torchvision/models/segmentation/segmentation.py)
```
Thanks

**Comment by yoshitomo-matsubara** [comment]
I think torchvision is >= 0.8.2

**Comment by andreamigliorati** [comment]
Thanks for the info!
